---
abstract: 'Test functions for Moose roles'
author:
  - 'Paul Boyd <pboyd@dev3l.net>'
build_requires:
  Test::Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Test-Role
requires:
  Carp: 0
  Exporter: 0
  List::Util: 0
  Moose: 0
  Test::Builder: 0
version: 0.02
